### ISSUE TITLE
Order by clause

### ISSUE THREAD

**Issue by tomislav12** [eddmash/powerorm#3]
Hi, 

I haven't found any docs about how to use order by clause with this ORM,
but I found the method and tried to use it with:
$roles = Role::objects()->all()->orderBy(['id']);
And it gives me error: 

A PHP Error was encountered
Severity: Warning
Message: array_slice() expects parameter 1 to be array, string given
Filename: Query/Query.php
Line Number: 857
Backtrace:
File: /var/www/.../vendor/eddmash/powerorm/src/Model/Query/Query.php
Line: 857
Function: array_slice 

Do you know if this is a bug, or wrong usage?
Regards

**Comment by eddmash** [comment]
the usage is correct, might be a bug, i will checkt it out.

Thank you for the feedback

regards.

**Comment by eddmash** [comment]
fixed with the  [2beb13e520](https://github.com/eddmash/powerorm/commit/2beb13e520a1da20aa78979b52adcd1e48ba1368)
